---
- name: Keepalived X Haproxy X Nginx Web Server on Docker
  hosts: all
  become: true
  become_method: sudo
  vars:
    - virtual_ip: 192.168.200.36
    - lb1_ip: 192.168.200.37
    - lb2_ip: 192.168.200.38
    - web1_ip: 192.168.200.39
    - web2_ip: 192.168.200.40
    - interface: "{{ ansible_default_ipv4.interface }}"
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: 'yes'
        state: present
        force_apt_get: true
        update_cache: true
        cache_valid_time: 86400

    - name: Set timezone
      ansible.builtin.timezone:
        name: Asia/Jakarta

    - name: Install required packages
      ansible.builtin.apt:
        state: present
        update_cache: true
        pkg:
          - keepalived
          - haproxy
          - chrony
          - net-tools
      notify: Restart chrony
      when: inventory_hostname in groups['keepalived']

    - name: Enable IP forwarding
      ansible.builtin.copy:
        src: keepalived.conf
        dest: "/etc/sysctl.d/keepalived.conf"
        mode: 0644
        backup: true
      notify: Reload sysctl
      when: inventory_hostname in groups['keepalived']

    - name: Create keepalived.conf for keepalived1
      ansible.builtin.template:
        src: keepalived01.conf
        dest: /etc/keepalived/keepalived.conf
        mode: 0644
        backup: true
      when: inventory_hostname == 'Keepalived1'
      notify: Restart keepalived

    - name: Create keepalived.conf for keepalived2
      ansible.builtin.template:
        src: keepalived02.conf
        dest: /etc/keepalived/keepalived.conf
        mode: 0644
        backup: true
      when: inventory_hostname == 'Keepalived2'
      notify: Restart keepalived

    - name: Create haproxy.cfg file
      ansible.builtin.template:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644
        backup: true
      notify: Restart haproxy
      when: inventory_hostname in groups['keepalived']

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      when: inventory_hostname in groups['webserver']

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present
      when: inventory_hostname in groups['webserver']

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker
        state: present
      when: inventory_hostname in groups['webserver']

    - name: Install required packages for docker
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - gnupg-agent
          - gnupg
          - python3-pip
          - python3-docker
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      notify: Restart docker
      when: inventory_hostname in groups['webserver']

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Deploy nginx docker container
      community.docker.docker_container:
        container_default_behavior: no_defaults
        image: nginx:stable
        name: nginx-web-server
        state: started
        restart: true
        restart_policy: always
        ports:
          - "81:80"
      when: inventory_hostname in groups['webserver']

  handlers:
    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

    - name: Restart chrony
      ansible.builtin.service:
        name: chrony
        state: restarted
        enabled: true

    - name: Reload sysctl
      ansible.builtin.command: sysctl --system

    - name: Restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted
        enabled: true

    - name: Restart haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted
        enabled: true
...
