- name: Keepalived X Haproxy
  hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: Update system
      apt:
        name: "*"
        state: present
        update_cache: true

    - name: Install common packages
      apt:
        state: present
        update_cache: true
        pkg:
          - chrony
          - keepalived
          - haproxy

    - name: Set timezone
      timezone:
        name: Asia/Jakarta

    - name: Enable and restart chrony
      service:
        name: chrony
        state: restarted
        enabled: true

    - name: Enable IP forwarding
      copy:
        dest: "/etc/sysctl.conf"
        content: |
          net.ipv4.ip_forward=1
          net.ipv4.ip_nonlocal_bind=1
        mode: 0644

    - name: Reload sysctl
      command: sysctl -p

#======================================================================================#

- name: Set config file keepalived.conf LB1
  hosts: lb01
  become: true
  become_method: sudo
  tasks:

    - name: Create keepalived.conf
      template: 
        src: keepalived01.conf 
        dest: /etc/keepalived/keepalived.conf
        mode: 0644
      
    - name: Restart and enable keeplived
      service:
        name: keepalived
        state: restarted
        enabled: true

#======================================================================================#

- name: Set config file keepalived.conf LB2
  hosts: lb02
  become: true
  become_method: sudo
  tasks:
    
    - name: Create keepalived.conf
      template:
        src: keepalived02.conf
        dest: /etc/keepalived/keepalived.conf
        mode: 0644
        
    - name: Restart and enable keeplived
      service:
        name: keepalived
        state: restarted
        enabled: true
