---
- name: Keepalived X Haproxy X Nginx Web Server on Docker
  hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: Update and upgrade apt packages
      apt:
        upgrade: 'yes'
        state: present
        force_apt_get: true
        update_cache: true
        cache_valid_time: 86400

    - name: Install chrony
      apt:
        name: chrony
        state: present
        update_cache: true

    - name: Set timezone
      timezone:
        name: Asia/Jakarta

    - name: Enable and restart chrony
      service:
        name: chrony
        state: restarted
        enabled: true

    - name: Install keepalived and haproxy
      apt:
        state: present
        update_cache: true
        pkg:
          - keepalived
          - haproxy
      when: inventory_hostname in groups['keepalived']

    - name: Enable IP forwarding
      copy:
        dest: "/etc/sysctl.conf"
        content: |
          net.ipv4.ip_forward=1
          net.ipv4.ip_nonlocal_bind=1
        mode: 0644
        backup: true
      when: inventory_hostname in groups['keepalived']
      register: sysctl_conf

    - name: Reload sysctl
      command: sysctl -p
      register: output
      changed_when: output.rc != 1
      when: inventory_hostname in groups['keepalived'] and sysctl_conf.changed

    - name: Create keepalived.conf for keepalived1
      template:
        src: keepalived01.conf
        dest: /etc/keepalived/keepalived.conf
        mode: 0644
      when: ansible_hostname == 'keepalived1'
      register: keepalived01_conf

    - name: Create keepalived.conf for keepalived2
      template:
        src: keepalived02.conf
        dest: /etc/keepalived/keepalived.conf
        mode: 0644
      when: ansible_hostname == 'keepalived2'
      register: keepalived02_conf

    - name: Restart and enabled keepalived
      service:
        name: keepalived
        state: restarted
        enabled: true
      when: (ansible_hostname == 'keepalived1' and keepalived01_conf.changed) or (ansible_hostname == 'keepalived2' and keepalived02_conf.changed)

    - name: Create haproxy.cfg file
      template:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644
        backup: true
      when: inventory_hostname in groups['keepalived']
      register: haproxy_cfg

    - name: Restart and enabled haproxy
      service:
        name: haproxy
        state: restarted
        enabled: true
      when: inventory_hostname in groups['keepalived'] and haproxy_cfg.changed

    - name: Install required dependencies for docker
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - gnupg-agent
          - gnupg
          - python3-pip
          - python3-docker
        state: present
        update_cache: true
      when: inventory_hostname in groups['webserver']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present
      when: inventory_hostname in groups['webserver']

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker
        state: present
      when: inventory_hostname in groups['webserver']

    - name: Install Docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      when: inventory_hostname in groups['webserver']

    - name: Enable and restart docker
      service:
        name: docker
        state: restarted
        enabled: true
      when: inventory_hostname in groups['webserver']

    - name: Deploy nginx docker container
      docker_container:
        container_default_behavior: no_defaults
        image: nginx:stable
        name: nginx-web-server
        state: started
        restart: true
        restart_policy: always
        ports:
          - "81:80"
      when: inventory_hostname in groups['webserver']
...
